# Generated by Django 6.0.3 on 2026-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_carrito_actualizado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='precio_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
