# Generated by Django 5.2.13 on 2026-06-09 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('sector', models.CharField(choices=[('Atención al cliente', 'Atención al cliente'), ('Caja', 'Caja'), ('Reposición', 'Reposición'), ('Seguridad', 'Seguridad'), ('Limpieza', 'Limpieza'), ('Administración', 'Administración')], default='atencion', max_length=20)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares_empleados/')),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['sector', 'usuario__username'],
            },
        ),
    ]
