# Generated by Django 6.0.3 on 2026-03-11 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField(default=0)),
                ('es_cliente_premium', models.BooleanField(default=False)),
                ('saldo_a_favor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preferencias', models.ManyToManyField(blank=True, related_name='clientes_interesados', to='productos.categoria')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
